openapi: 3.0.3
info:
  title: ASM Proyecto 2 
  version: '1.0'
servers:
  - url: http://localhost:{port}
    description: ASM
    variables:
      port:
        default: '8000'
paths:
  /crear_pool/{pool_name}:
    post:
      summary: Crear pool con nombre provisto
      parameters:
        - schema:
            type: string
          name: pool_name
          in: path
          required: true
      responses:
        '200':
          description: Pool Creado
          content:
            application/json: { }
        '424':
          description: Failed dependency ASM
          content:
            application/json: { }
      description: crear pool
      operationId: crear_pool
      x-openapi-router-controller: app.controllers
      tags:
        - crear_pool
  /eliminar_pool/{pool_name}:
    post:
      summary: eliminar pool de auto-escalamiento
      parameters: 
        - schema:
            type: string
          name: pool_name
          in: path
          required: true
      responses:
        '200':
          description: Pool e instancias eliminado
          content:
            application/json: {}
        '424':
          description: Error de ASM
          content:
            application/json: { }
      description: eliminar pool
      operationId: eliminar_pool
      x-openapi-router-controller: app.controllers
      tags:
        - eliminar_pool